const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  search:           (p, q)        => ipcRenderer.invoke('fs:search', p, q),
  smartScan:        (p, type, opt)=> ipcRenderer.invoke('fs:smartScan', p, type, opt),
  cleanDsStore:     (p)           => ipcRenderer.invoke('fs:cleanDsStore', p),
  diskBreakdown:    (p)           => ipcRenderer.invoke('fs:diskBreakdown', p),
  readdir:          (p)           => ipcRenderer.invoke('fs:readdir', p),
  subdirs:          (p)           => ipcRenderer.invoke('fs:subdirs', p),
  stat:             (p)           => ipcRenderer.invoke('fs:stat', p),
  readText:         (p)           => ipcRenderer.invoke('fs:readText', p),
  writeFile:        (p, c)        => ipcRenderer.invoke('fs:writeFile', p, c),
  rename:           (p, n)        => ipcRenderer.invoke('fs:rename', p, n),
  copy:             (srcs, dest)  => ipcRenderer.invoke('fs:copy', srcs, dest),
  move:             (srcs, dest)  => ipcRenderer.invoke('fs:move', srcs, dest),
  createFile:       (p)           => ipcRenderer.invoke('fs:create-file', p),
  createFolder:     (p)           => ipcRenderer.invoke('fs:create-folder', p),
  delete:           (srcs)        => ipcRenderer.invoke('fs:delete', srcs),
  trashItem:        (srcs)        => ipcRenderer.invoke('fs:trashItem', srcs),
  openTrash:        ()            => ipcRenderer.invoke('fs:openTrash'),
  emptyTrash:       ()            => ipcRenderer.invoke('fs:emptyTrash'),
  openTerminal:     (dir)         => ipcRenderer.invoke('fs:openTerminal', dir),
  openEditor:       (p)           => ipcRenderer.invoke('fs:openEditor', p),
  compressZip:      (srcs)        => ipcRenderer.invoke('fs:compressZip', srcs),
  copyToClipboard:  (text)        => ipcRenderer.invoke('clipboard:write', text),
  openFile:         (p)           => ipcRenderer.invoke('fs:openFile', p),
  getAlbumArt:      (p)           => ipcRenderer.invoke('fs:getAlbumArt', p),
  getHomeDirs:      ()            => ipcRenderer.invoke('fs:getHomeDirs'),
  getiCloudPath:    ()            => ipcRenderer.invoke('fs:getiCloudPath'),
  openFolderDialog: ()            => ipcRenderer.invoke('dialog:openFolder'),
  pathJoin:         (...args)     => args.join('/').replace(/\/+/g, '/'),
  basename:         (p)           => p.split('/').pop(),
  dirname:          (p)           => { const parts = p.split('/'); parts.pop(); return parts.join('/') || '/'; },
  newWindow:        (startPath)   => ipcRenderer.invoke('new-window', startPath),
  closeWindow:      ()            => ipcRenderer.invoke('window:close'),
  onNavigateTo:     (callback)    => ipcRenderer.on('navigate-to', (_e, path) => callback(path)),
  showContextMenu:  (opts)        => ipcRenderer.send('show-context-menu', opts),
  onContextAction:  (callback)    => ipcRenderer.on('context-menu-action', (_e, action) => callback(action))
});

