blank_issues_enabled: true
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/Jraucog/finderview/discussions
    about: Ask questions, share ideas, and connect with the community.
